// flow-typed signature: 5f7ce2bfacc462dedf89ea6a1fe88d2f
// flow-typed version: <<STUB>>/sanctuary_v0.14.x/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanctuary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanctuary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sanctuary/index' {
  declare module.exports: $Exports<'sanctuary'>;
}
declare module 'sanctuary/index.js' {
  declare module.exports: $Exports<'sanctuary'>;
}
